/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package juno;

import juno.controller.TodoController;
import juno.model.TodoEntity;
import juno.repository.IRepository;
import juno.repository.InMemoryRepository;

import java.io.Console;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        System.out.println(System.console());
//        if(System.console() == null) {
//            System.out.println("No console found");
//            return;
//        }
        IRepository repository = new InMemoryRepository<Integer, TodoEntity>();
        Scanner console = new Scanner(System.in);
        TodoController controller = new TodoController(repository, console);
        try {
            controller.run();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
//        controller.showRepository();
    }
}
