/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package juno;

import juno.controller.TodoController;
import juno.model.TodoEntity;
import juno.repository.IRepository;
import juno.repository.JDBCRepository;

import java.io.Console;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        IRepository repository = new InMemoryRepository<Integer, TodoEntity>();
        IRepository repository = new JDBCRepository<Integer, TodoEntity>();
//        try {
//            Serializer.deserializeCsv(repository, "saved-todos.csv");
//        } catch (Exception e) {
//            throw new RuntimeException(e);
//        }

        Scanner console = new Scanner(System.in);
        TodoController controller = new TodoController(repository, console);
        try {
            controller.run();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
//        controller.showRepository();
    }
}
