/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package juno;

import juno.controller.TodoController;
import juno.model.TodoEntity;
import juno.repository.IRepository;
import juno.repository.InMemoryRepository;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if(System.console() == null) {
            System.out.println("No console found");
            return;
        }
        IRepository repository = new InMemoryRepository<Integer, TodoEntity>();
        TodoController controller = new TodoController(repository);
        controller.run();
    }
}
